# Generated by Django 5.0.6 on 2024-06-19 01:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_comment_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
