# Generated by Django 5.0.6 on 2024-06-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_category_name_alter_class_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Lesson',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='class_fk',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='class_fk',
            new_name='lesson',
        ),
    ]
