# Generated by Django 5.0.6 on 2024-06-19 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_save_created_at_save_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('user', 'lesson')},
        ),
    ]
