# Generated by Django 5.0.6 on 2024-06-19 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_comment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watched',
            name='watched_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
