# Generated by Django 5.0.6 on 2024-06-20 18:57

import course.models.utils.validators.field_not_numeric_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_lesson_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[course.models.utils.validators.field_not_numeric_validator.validate_not_numeric]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, unique=True, validators=[course.models.utils.validators.field_not_numeric_validator.validate_not_numeric]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=50, unique=True, validators=[course.models.utils.validators.field_not_numeric_validator.validate_not_numeric]),
        ),
    ]
