from .category_serializer_v1 import CategorySerializerV1
from .course_serializer_v1 import CourseSerializerV1
from .lesson_serializer_v1 import LessonSerializerV1
from .comment_serializer_v1 import CommentSerializerV1
from .save_serializer_v1 import SaveSerializerV1
from .watched_serializer_v1 import WatchedSerializerV1